[general]
import = [
  "~/.config/alacritty/github/light.toml",
  "~/.config/alacritty/keybindings.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

# [mouse]
# hide_cursor_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 100000
multiplier = 3

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"

[window.dimensions]
columns = 201
lines = 48

[window.padding]
x = 6
y = 6

[window.position]
x = 0
y = 0
